import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { analyzeTrace } from '../src/analyze.ts';
import { buildSummary, serializeSummary } from '../src/summary.ts';

// End-to-end: run the whole analyze → summary pipeline against the committed,
// clipped fixtures and assert it reproduces the golden summary byte-for-byte.
// Everything here is committed (fixtures + goldens), so this runs in CI — no
// reliance on the large, gitignored real traces.
//
// Fixtures are real traces clipped to a small coherent slice by
// `scripts/make-fixture.ts`; goldens are regenerated by
// `scripts/snapshot-fixtures.ts`. If a model change shifts the numbers,
// regenerate the goldens and review the diff.

const FIXTURE_DIR = join(import.meta.dirname, 'fixtures');
const fixtures = readdirSync(FIXTURE_DIR).filter((f) => f.endsWith('.trace.json.gz'));

describe('analyze pipeline reproduces the committed fixture summaries', () => {
  it('has fixtures to run against', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  for (const trace of fixtures) {
    it(`${trace} reproduces its golden summary`, async () => {
      const analysis = await analyzeTrace(join(FIXTURE_DIR, trace));
      // Pass the bare filename (not the absolute path) so the golden's `trace`
      // field — and thus the whole file — is machine-independent.
      const produced = serializeSummary(buildSummary(trace, analysis));
      const goldenPath = join(
        FIXTURE_DIR,
        trace.replace(/\.trace\.json\.gz$/, '.summary.json'),
      );
      expect(produced).toBe(readFileSync(goldenPath, 'utf8'));
    });
  }
});
